site_name: docs.blackbeard.media
site_url: https://docs.blackbeard.media/

repo_name: docs
repo_url: https://github.com/Blackbeard-Media/docs/

theme:
  name: material
  icon:
    logo: material/library
    repo: fontawesome/brands/github
    
  language: en

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - Home: index.md
  
  - Guides:
    - Plex:
      - Accepting your Plex invitation: guides/plex/accepting-your-invite.md
      - How to Navigate and use Plex: guides/plex/navigating-plex.md
    - Account:
      - How to manage your Blackbeard account: guides/account/manage-your-account.md
      - How to link your Discord account: guides/account/linking-your-discord.md
    - Requests:
      - How to request content via Overseerr: guides/requests/overseerr-requests.md
      - How to request content via Discord: guides/requests/discord-requests.md
      - How to request content that is Anime: guides/requests/anime-requests.md
  - Clients: 
    - Apple TV: clients/appletv.md
    - Browser: clients/browser.md
    - Desktop: clients/desktop.md
    - Mobile: clients/mobile.md
    - Television: clients/television.md
    - Console: clients/console.md
    - Other: clients/other.md
