site_name: Blackbeard Media
site_url: https://docs.blackbeard.media/

repo_name: docs
repo_url: https://github.com/Blackbeard-Media/docs/

theme:
  name: material
  icon:
    logo: material/library
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.tabs
    
  language: en

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - Home: index.md
  - What is Plex: home/what-is-plex.md
  - Plex:
    - Creating a Plex Account: guides/plex/creating-an-account.md
    - Accepting your Plex invitation: guides/plex/accepting-your-invite.md
    - Navigating and using Plex: guides/plex/navigating-plex.md
    - Recommended Settings: guides/plex/recommended-settings.md
  - Appboxes:
    - How to manage your Blackbeard account: guides/account/manage-your-account.md
    - How to link your Discord account: guides/account/linking-your-discord.md
  - Client Settings: 
    - Amazon Firestick/TV: clients/firetv.md
    - Android Mobile: clients/android.md
    - Android TV: clients/androidtv.md
    - Apple iOS: clients/appleios.md
    - Apple TV: clients/appletv.md
    - Browser: clients/browser.md
    - Plex Media Player: clients/desktop.md
    - PS4/5 / Xbox: clients/console.md
    - Roku: clients/roku.md
    - Smart TV: clients/television.md
    - Other: clients/other.md
