site_name: Blackbeard Media
site_url: https://docs.blackbeard.media/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
  - def_list
  - abbr
  - tables
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - glightbox
  
theme:
  name: material
  icon:
    logo: material/library
    repo: fontawesome/brands/discord
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.tabs
    - content.tooltips
    - navigation.footer
    - toc.integrate    

extra:
  generator: false
  social:
  - icon: fontawesome/solid/heart
    class: md-social__link heart
    link: 'https://donate.blackbeard.media'
    name: Donate
  - icon: fontawesome/brands/discord
    class: md-social__link
    link: 'https://discord.blackbeard.media'
    name: Discord

  language: en

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - Home: index.md
  - Plex: 
    - What Is Plex?: plex/what-is-plex.md
    - Getting Started: plex/getting-started.md
    - Libaries / Navigation: plex/libraries.md
    - Playback / Playback Quality: plex/playback.md
    - Requests: plex/requests.md
    - Things to Consider: plex/things-to-consider.md
  - Shares:
    - Creating a Plex Account: plex/creating-your-account.md
    - Accepting your Plex invitation: plex/accepting-your-invite.md
    - Recommended Client Settings: clients/index.md
  - Appboxes:
    - How to manage your Blackbeard account: guides/account/manage-your-account.md
    - How to link your Discord account: guides/account/linking-your-discord.md
  - Client Settings: 
    - Amazon Firestick/TV: clients/firetv.md
    - Android Mobile: clients/android.md
    - Android TV: clients/androidtv.md
    - Apple iOS: clients/appleios.md
    - Apple TV: clients/appletv.md
    - Browser: clients/browser.md
    - Plex Media Player: clients/desktop.md
    - PS4/5 / Xbox: clients/console.md
    - Roku: clients/roku.md
    - Smart TV: clients/television.md
    - Other: clients/other.md
