site_name: Blackbeard Media
site_url: https://docs.blackbeard.media/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
  - def_list
  - abbr
  - tables
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - glightbox
  - typeset
  - meta
  - search:
      lang: en
  
theme:
  name: material
  icon:
    logo: material/pirate
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.tabs
    - navigation.expand
    - content.tooltips
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    - navigation.top
    - announce.dismiss
    - content.code.copy
    - content.code.select
    - content.code.annotate 
    
  palette:
   
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference       
extra:
  generator: false
  social:
  - icon: fontawesome/solid/heart
    class: md-social__link heart
    link: 'https://donate.blackbeard.media'
    name: Donate
  - icon: fontawesome/brands/discord
    class: md-social__link
    link: 'https://discord.blackbeard.media'
    name: Discord
  language: en

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Plex: 
    - What Is Plex?: plex/what-is-plex.md
    - Getting Started: plex/getting-started.md
    - Libaries / Navigation: plex/libraries.md
    - Playback / Playback Quality: plex/playback.md
    - Things to Consider: plex/things-to-consider.md
  - Shares:
    - Getting Started: shares/getting-started.md
    - Tools: shares/tools.md
  - Appboxes:
    - Getting Started: appboxes/getting-started.md
    - Kronos: appboxes/kronos.md
    - Tautulli: appboxes/tautulli.md
    - Plex Meta Manager: appboxes/pmm.md
  - FAQ:
    - Table of Contents: faq/index.md
    - Appboxes: faq/appboxes.md
    - Shares: faq/shares.md
    - Requests: faq/requests.md
  - Troubleshooting / Tips:
    - General: troubleshooting/index.md
    - Plex Client:
      - Troubleshooting: troubleshooting/client/index.md
      - Tips: troubleshooting/client/tips.md
    - Appboxes:
      - Troubleshooting: troubleshooting/server/index.md
      - Settings: troubleshooting/server/settings.md
  - Client Settings: 
    - Amazon FireTV: clients/firetv.md
    - Android Mobile: clients/android.md
    - Android TV: clients/androidtv.md
    - Apple iOS: clients/ios.md
    - Apple TV: clients/appletv.md
    - Kodi: clients/kodi.md
    - LG / WebOS: clients/lg.md
    - Plex Media Player: clients/pmp.md
    - Plex Web Player: clients/web.md
    - PlayStation / Xbox: clients/console.md
    - Roku: clients/roku.md
    - Other: clients/other.md
